services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ai-webui
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - webui_data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://192.168.1.2:11434

volumes:
  webui_data:
    driver: local 