---
# Ubuntu Cloud Image Configuration
is_present: true
ubuntu_release: "noble"
ubuntu_arch: "amd64"
image_url: "https://cloud-images.ubuntu.com/{{ ubuntu_release }}/current/{{ ubuntu_release }}-server-cloudimg-{{ ubuntu_arch }}.img"
image_name: "ubuntu-{{ ubuntu_release }}-server-cloudimg-{{ ubuntu_arch }}.img"

# Proxmox Configuration
storage_name: "data-2"
vm_id: "{{ vm_prefix_id + 10 }}"
template_name: "ubuntu-{{ ubuntu_release }}-template"