---
# Ubuntu Cloud Image Configuration
is_present: true
ubuntu_release: "noble"
ubuntu_arch: "amd64"
image_url: "https://cloud-images.ubuntu.com/{{ ubuntu_release }}/current/{{ ubuntu_release }}-server-cloudimg-{{ ubuntu_arch }}.img"
image_name: "ubuntu-{{ ubuntu_release }}-server-cloudimg-{{ ubuntu_arch }}.img"

# Proxmox Configuration
storage_name: "disk500mb-01"
vm_template_id: "{{ vm_prefix_id + 10 }}"
vm_net_bridge: "vmbr0"
template_name: "ubuntu-{{ ubuntu_release }}-template"

# Cloud-init configuration
cloud_init_user: "{{ ansible_user }}"
cloud_init_ssh_keys:
  - "{{ lookup('env', 'ANSIBLE_SSH_KEY_PUB') | default('ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzUXlDKjVBkd5g9HZmlElOJHaAhRSOACSe3N16JCMcj7w96opfwdrmq+wri9tUkyPQJeNknO83KtZyIeOwyTNcDAuDS27UWPHCv1qLCr2xk7iUXe+8hW7DisuVJ2/GOkdqxwjto3a8Npvc3gHJmrvKDLqiRaal6pxkVTwA/peMjLIKrEc6NATY4+Uu/EGNDbo9dToqmQyvD/iArz5+1kwG0VD4x1PXzBmTsv7PC6QDEciMN/TcXAKaN3oqtOm0wheYYInFy36yQEP4lgRwTUseMr1hSzpdpi3eN2BujB1zzDxWvN+NN3GdWVvdabbb2ORkC2F/XgTUu9UHffKDJreF7rJ66nKORcgMxuBBv9fOj1yXM1topsBFNfI+R+YDkSJozgfZCZHQUbzXiuzDyLtfA3fGcT4k1pja19OpodVrimoxsHAzoeQo2hyBDtPdOrXUEsZNeY4Mh2hkGYwrdXarsuhW2oUsrQrr2qByzlvQITf9PCdpACxcxpJEVNctUBk=') }}"
