---
# Ubuntu Cloud Image Configuration
is_present: true
ubuntu_release: "noble"
ubuntu_arch: "amd64"
image_url: "https://cloud-images.ubuntu.com/{{ ubuntu_release }}/current/{{ ubuntu_release }}-server-cloudimg-{{ ubuntu_arch }}.img"
image_name: "ubuntu-{{ ubuntu_release }}-server-cloudimg-{{ ubuntu_arch }}.img"

# Proxmox Configuration
storage_name: "data-2"
vm_template_id: "{{ vm_prefix_id + 10 }}"
vm_net_bridge: "vmbr0"
template_name: "ubuntu-{{ ubuntu_release }}-template"

# Cloud-init configuration
cloud_init_user: "{{ ansible_user }}"
cloud_init_ssh_key: "{{ lookup('env', 'ANSIBLE_SSH_KEY_PUB') }}" 
