---
# VM Basic Configuration
vm_is_present: true
vm_template_id: "{{ vm_prefix_id + 10 }}"
vm_template: "ubuntu-noble-template"
vm_name: "vm-{{ vm_id}}"
vm_description: "VM created by Ansible"

# VM Hardware Configuration
vm_cores: 2
vm_memory: 2048
vm_disk_size: "40G"

# VM Hardware Options
vm_cpu_type: "host"
vm_numa: false
vm_hotplug: "disk,network,usb"
vm_ostype: "l26"  # Linux 2.6+
vm_machine_type: "q35"

# VM Boot and Startup Options
vm_onboot: true

# QEMU Guest Agent
vm_qemu_agent: true

# Advanced Options
vm_protection: false
vm_ballooning: true
vm_tablet: true

# Template and Clone Options
vm_full_clone: true

# Post-Creation Options
vm_start_after_create: true
vm_wait_for_guest_agent: true
vm_wait_timeout: 300

# Network and Storage (referenced in debug output)
vm_storage: "local-lvm"
vm_net_bridge: "vmbr0"

 