---
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    env_file: ".env"
    environment:
      - ServerIP=${SERVER_IP}
      - TZ=${TZ}
      - WEBPASSWORD=${WEBPASSWORD}
      - PIHOLE_DNS_1=${PIHOLE_DNS_1}
      - PIHOLE_DNS_2=${PIHOLE_DNS_2}
      - INTERFACE=${PIHOLE_INTERFACE}
      - DHCP_ACTIVE=${DHCP_ACTIVE}
      - DHCP_START=${DHCP_START}
      - DHCP_END=${DHCP_END}
      - DHCP_ROUTER=${DHCP_ROUTER}
      - DHCP_LEASETIME=${DHCP_LEASETIME}
      - PIHOLE_DOMAIN=${PIHOLE_DOMAIN}
      - PXE_SERVER_IP=${PXE_SERVER_IP}
    volumes:
      - ./pihole/etc:/etc/pihole
      - ./pihole/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: always

