version: '3.8'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: '{{ PIHOLE_TIMEZONE }}'
      WEBPASSWORD: '${PIHOLE_ADMIN_PASSWORD:-admin123}'
      PIHOLE_DNS_: '1.1.1.1;8.8.8.8'
      DNSMASQ_LISTENING: 'all'
      PIHOLE_DOMAIN: '{{ PIHOLE_DOMAIN }}'
      ServerIP: '{{ PIHOLE_SERVER_IP }}'
    volumes:
      - './config/pihole:/etc/pihole'
      - './config/dnsmasq.d:/etc/dnsmasq.d'
      - './config/custom.list:/etc/pihole/custom.list'
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - pihole-network

networks:
  pihole-network:
    driver: bridge 