---
- name: Create Ubuntu Template in Proxmox
  hosts: "{{ target }}"
  become: yes
  tasks:
    - name: Create Ubuntu Template
      include_role:
        name: provision/proxmox/image-templates/ubuntu
      tags:
        - template
        - ubuntu
        - proxmox
