---
- name: Ensure resolv.conf exists
  file:
    path: /etc/resolv.conf
    state: touch
    mode: "0644"
  ignore_errors: true

- name: Set DNS resolver
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver {{ nameserver }}"
    create: yes
    state: present
  loop: "{{ resolved.nameservers }}"
  loop_control:
    loop_var: nameserver
  ignore_errors: true

- name: Restart resolver
  systemd:
    name: systemd-resolved
    state: restarted