---
- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add present users to docker group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: docker
    append: yes