---
- name: Terminate active processes for absent users
  ansible.builtin.shell: |
    if id "{{ user.name }}" >/dev/null 2>&1; then
      pkill -KILL -u "{{ user.name }}" || true
    fi
  register: remove_user_processes
  changed_when: remove_user_processes.stdout != "" or remove_user_processes.stderr != ""
  failed_when: false

- name: Ensure absent users are absent
  ansible.builtin.user:
    name: "{{ user.name }}"
    state: absent
    remove: yes

- name: Ensure absent groups are absent
  ansible.builtin.group:
    name: "{{ user.name }}"
    state: absent

- name: Ensure sudoers.d files for absent users are removed
  ansible.builtin.file:
    path: /etc/sudoers.d/{{ user.name }}
    state: absent
