---
- name: Test Infrastructure Playbook
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Display system information
      debug:
        msg: "Running on {{ ansible_hostname }} ({{ ansible_os_family }})"

    - name: Check disk space
      shell: df -h
      register: disk_space
      changed_when: false

    - name: Display disk space
      debug:
        var: disk_space.stdout_lines

    - name: Display OK message  
      debug:
        msg: "Successfully completed the playbook"