---
dependencies:
  - role: ../image-templates/ubuntu
    vars:
      vm_template_id: "{{ vm_prefix_id + 10 }}"
      template_name: "{{ vm_template }}"
      is_present: true
    when: 
      - vm_template is defined
      - vm_template is regex('ubuntu.*template|.*ubuntu.*')
