version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-example
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge 