---

services:
  # Simple web server to serve iPXE scripts and OS files
  webserver:
    image: nginx:alpine
    container_name: pxe-webserver
    network_mode: "host"
    ports:
      - "80:80"
    volumes:
      - ./assets:/usr/share/nginx/html
    restart: always

  dnsmasq:
    build: ./dnsmasq
    container_name: dnsmasq
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/udp"
      - "67:67/udp"
      - "69:69/udp"
    environment:
      - DHCP_INTERFACE=eth0
      - DHCP_RANGE_START=192.168.1.50
      - DHCP_RANGE_END=192.168.1.250
      - DHCP_LEASE_TIME=12h
      - DHCP_GATEWAY=192.168.1.1
      - PXE_IP_ADDRESS=192.168.1.3
      - PXE_SCRIPT=parrot-live.ipxe
    volumes:
      - ./assets:/assets
    restart: always
