---

services:
  pxe-server:
    build: 
      context: ./src
      args:
        PXE_IP_ADDRESS: ${PXE_IP_ADDRESS}
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    container_name: pxe-server
    ports:
      - "53:53/udp"
      - "67:67/udp" 
      - "69:69/udp"
      - "80:80"
    environment:
      - DHCP_INTERFACE=${DHCP_INTERFACE}
      - DHCP_RANGE_START=${DHCP_RANGE_START}
      - DHCP_RANGE_END=${DHCP_RANGE_END}
      - DHCP_LEASE_TIME=${DHCP_LEASE_TIME}
      - DHCP_GATEWAY=${DHCP_GATEWAY}
      - PXE_IP_ADDRESS=${PXE_IP_ADDRESS}
      - PXE_AUTO_OS=${PXE_AUTO_OS:-ubuntu}
      - PXE_BOOT_HOSTNAME=${PXE_BOOT_HOSTNAME:-node}
      - PXE_BOOT_SSH_KEY=${PXE_BOOT_SSH_KEY}
      - PXE_BOOT_PASS=${PXE_BOOT_PASS:-password}
      - PXE_BOOT_USER=${PXE_BOOT_USER:-admin}
      - PXE_BOOT_INTERFACE=${PXE_BOOT_INTERFACE:-eth0}
    volumes:
      - ./share:/share
    restart: always
