---

services:
  pxe-server:
    build: 
      context: ./src
      args:
        PXE_SCRIPT: parrot-live.ipxe
    container_name: pxe-server
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/udp"
      - "67:67/udp" 
      - "69:69/udp"
      - "80:80"
    environment:
      - DHCP_INTERFACE=eth0
      - DHCP_RANGE_START=192.168.1.50
      - DHCP_RANGE_END=192.168.1.250
      - DHCP_LEASE_TIME=12h
      - DHCP_GATEWAY=192.168.1.1
      - PXE_IP_ADDRESS=192.168.1.10
    restart: always