---

services:
  pxe-server:
    build: 
      context: ./src
      args:
        PXE_IP_ADDRESS: ${PXE_IP_ADDRESS}
        PXE_SCRIPT: ${PXE_SCRIPT}
    container_name: pxe-server
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/udp"
      - "67:67/udp" 
      - "69:69/udp"
      - "80:80"
    environment:
      - DHCP_INTERFACE=${DHCP_INTERFACE}
      - DHCP_RANGE_START=${DHCP_RANGE_START}
      - DHCP_RANGE_END=${DHCP_RANGE_END}
      - DHCP_LEASE_TIME=${DHCP_LEASE_TIME}
      - DHCP_GATEWAY=${DHCP_GATEWAY}
      - PXE_SCRIPT=${PXE_SCRIPT}
      - PXE_IP_ADDRESS=${PXE_IP_ADDRESS}
    restart: always
