apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  config: |
    containerRuntimeExecutor: docker
    artifactRepository:
      s3:
        bucket: argo-workflows
        endpoint: minio:9000
        insecure: true
        accessKeySecret:
          name: minio-credentials
          key: accesskey
        secretKeySecret:
          name: minio-credentials
          key: secretkey
    persistence:
      postgresql:
        host: postgres
        database: ${POSTGRES_DB}
        tableName: argo_workflows
        userNameSecret:
          name: postgres-credentials
          key: username
        passwordSecret:
          name: postgres-credentials
          key: password 