name: Deploy Jenkins

on:
  push:
    branches: [ main ]
    paths:
      - 'jenkins/**'
      - '.github/workflows/deploy-jenkins.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Jenkins
        uses: ./.github/actions/deploy-docker-compose
        with:
          server_host: ${{ secrets.JENKINS_SERVER_HOST }}
          server_username: ${{ secrets.JENKINS_SERVER_USERNAME }}
          server_port: ${{ secrets.JENKINS_SERVER_PORT }}
          server_ssh_key: ${{ secrets.JENKINS_SERVER_SSH_KEY }}
          service_name: 'jenkins'
          source_path: 'jenkins'