name: Deploy Jenkins

on:
  push:
    branches: [ main ]
    paths:
      - 'jenkins/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Jenkins Agent
        uses: ./.github/actions/deploy-docker-compose
        with:
          server_host: 'jenkins'
          service_name: 'jenkins'
          source_path: 'jenkins'
          
          server_username: ${{ secrets.DEFAULT_SSH_USER }}
          server_port: ${{ secrets.DEFAULT_SSH_PORT }}
          server_ssh_key: ${{ secrets.DEFAULT_SSH_KEY }}
