name: Deploy Front Service

on:
  push:
    paths:
      - 'front-proxy/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          cd front-proxy
          npm install
      
      - name: Build
        run: |
          cd front-proxy
          npm run build
      
      - name: Deploy to Cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          cd front-proxy
          npm install -g wrangler
          wrangler --version
          wrangler deploy 