name: Deploy Reverse Proxy

on:
  push:
    branches: [ main ]
    paths:
      - 'reverse-proxy/**'
      - '.github/workflows/deploy-reverse-proxy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Reverse Proxy
        uses: ./.github/actions/deploy-docker-compose
        with:
          server_host: ${{ secrets.REVERSE_PROXY_SERVER_HOST }}
          server_username: ${{ secrets.REVERSE_PROXY_SERVER_USERNAME }}
          server_port: ${{ secrets.REVERSE_PROXY_SERVER_PORT }}
          server_ssh_key: ${{ secrets.REVERSE_PROXY_SERVER_SSH_KEY }}
          service_name: 'reverse-proxy'
          source_path: 'reverse-proxy'
