version: "3.9"

services:
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    hostname: mysql
    volumes:
      - ./semaphore-mysql:/var/lib/mysql
    env_file:
      - ./.env
    network_mode: host

  semaphore:
    restart: unless-stopped
    image: semaphoreui/semaphore:latest
    volumes:
      - .vault_pass:/etc/.vault_pass:ro
      - .ssh-key:/etc/.ssh-key:ro
    env_file:
      - ./.env
    depends_on:
      - mysql
    network_mode: host